---
title: "BAMONA_Final_Code"
author: "Abby Robinson and Jess Herrmann"
date: "7/12/2022"
output: html_document
---
Load Package Libraries
```{r}
library(curl)
library(sf)
library(ggplot2)
library(ggmap)
library(sp)
library(adehabitatHR)
```

Use "curl" command to load and name data files from the GitHub repo for Battus philenor and all mimics 

```{r}
##   battus
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/battus_philenor.csv")
battus <- read.csv(b, header = TRUE, sep = ",")
battus
```

```{r}
##   limenitis 
l <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/limenitis_arthemis_astyanax.csv")
limenitis <- read.csv(l, header = TRUE, sep = ",")
limenitis
```

```{r}
##   glaucus
g <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/papilio_glaucus.csv")
glaucus <- read.csv(g, header = TRUE, sep = ",")
glaucus
```

```{r}
##   polyxenes
p <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/papilio_polyxenes.csv")
polyxenes <- read.csv(p, header = TRUE, sep = ",")
polyxenes
```

```{r}
##   troilus
t <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/papilio_troilus.csv")
troilus <- read.csv(t, header = TRUE, sep = ",")
troilus
```

```{r}
##   diana 
d <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/speyeria.diana.csv")
diana <- read.csv(d, header = TRUE, sep = ",")
diana
```
