---
title: "Jess_iNat_ranges"
author: "Jessica Herrmann"
date: "2022-11-10"
output: html_document
---
Load package libraries
```{r}
library(curl)
library(ggplot2)
library(MASS)
library(curl)
library(raster)
library(spatialEco)
library(lubridate)
library(rstudioapi)
library(ggmap)
```

Linking in API key
```{r}
register_google(key = "")
```

Loading/cleaning the data for each species
```{r}
### battus 
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/iNaturalist_battus_philenor_for_r.csv")
battus <- read.csv(b, header = TRUE, sep = ",")
head(battus)

length(battus$id) ### Sample size: 34,893
b <- subset(battus, select = c(id, observed_on, latitude, longitude, place_county_name, place_state_name, scientific_name) )
head(b)
battus <- na.omit(b)
length(battus$id) ### New sample size: 34,795
```

```{r}
##   limenitis 
l <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/iNaturalist_limenitis_arthemis_astyanax.csv")
limenitis <- read.csv(l, header = TRUE, sep = ",")
head(limenitis)

length(limenitis$id) ### Sample Size: 20,908
l <- subset(limenitis, select = c(id, observed_on, latitude, longitude, place_county_name, place_state_name, scientific_name) )
head(l)
limenitis <- na.omit(l)
length(limenitis$id) ###New Sample Size:20,855
```

```{r}
##   polyxenes
p <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/iNaturalist_papilio_polyxenes.csv")
polyxenes <- read.csv(p, header = TRUE, sep = ",")
head(polyxenes)

length(polyxenes$id) ### Sample Size: 58,735
p <- subset(polyxenes, select = c(id, observed_on, latitude, longitude, place_county_name, place_state_name, scientific_name) )
head(p)
polyxenes <- na.omit(p)
length(polyxenes$id) ###New Sample Size: 58,563
```

```{r}
##   troilus
t <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/iNaturalist_papilio_troilus.csv")
troilus <- read.csv(t, header = TRUE, sep = ",")
head(troilus)

length(troilus$id) ### Sample Size: 25,174
t <- subset(troilus, select = c(id, observed_on, latitude, longitude, place_county_name, place_state_name, scientific_name) )
head(t)
troilus <- na.omit(t)
length(troilus$id) ###New Sample Size: 25,077
```

```{r}
##   glaucus
g <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/iNaturalist_papilio_glaucus%20(version%201).xlsb.csv")
glaucus <- read.csv(g, header = TRUE, sep = ",")
head(glaucus)

length(glaucus$id) ### Sample Size: 66,657
g <- subset(glaucus, select = c(id, observed_on, latitude, longitude, place_county_name, place_state_name, scientific_name, morph) )
head(g)
glaucus <- na.omit(g)
length(glaucus$id) ###New Sample Size: 64,713

###### Separate only mimetic morphs 
glaucus <- subset(glaucus, morph == "black", drop = FALSE)
length(glaucus$id) ###Final Sample Size: 15,988
```

```{r}
##   diana 
d <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/iNaturalist_speyeria_diana_edited%20-%20Sheet1.csv")
diana <- read.csv(d, header = TRUE, sep = ",")
head(diana)

length(diana$id) ### Sample Size: 657
d <- subset(diana, select = c(id, sex, observed_on, latitude, longitude, place_county_name, place_state_name, scientific_name) )
head(d)

diana <- na.omit(d)
length(diana$id) ### New Sample Size: 651

###### Separate only mimetic morphs 
diana <- subset(diana, sex == "f", drop = FALSE)
length(diana$id) ### Final Sample Size: 186
```

Use the lubridate() package to separate data by years
```{r} 
## battus
bat.dates <- parse_date_time(battus$observed_on, "ymd")
bat.years <- year(bat.dates) # year() fxn creates separate column for years
battus$years <- bat.years # adds "years" column back into data set

# orders data set by "years" decreasing (most recent first)
battus <- battus[order(battus$years,decreasing=T),]
battus

# shows first and last six data points
head(battus)
tail(battus) #earliest year for Battus in iNat was 1973 (Texas)

# increases the max.print so we can see all data (otherwise R cuts it off at the first 1000 data points).
#options(max.print=1000000)
#battus$years
```

```{r} 
## limenitis
lim.dates <- parse_date_time(limenitis$observed_on, "ymd")
lim.years <- year(lim.dates)
limenitis$years <- lim.years

limenitis <- limenitis[order(limenitis$years,decreasing=T),]
limenitis

head(limenitis)
tail(limenitis) #earliest year is 1972 (Texas)
```
```{r} 
## polyxenes
pol.dates <- parse_date_time(polyxenes$observed_on, "ymd")
pol.years <- year(pol.dates)
polyxenes$years <- pol.years

polyxenes <- polyxenes[order(polyxenes$years,decreasing=T),]
polyxenes

head(polyxenes)
tail(polyxenes) #earliest year is 1953 (Arizona)
```
```{r} 
## troilus
tro.dates <- parse_date_time(troilus$observed_on, "ymd")
tro.years <- year(tro.dates)
troilus$years <- tro.years

troilus <- troilus[order(troilus$years,decreasing=T),]
troilus

head(troilus)
tail(troilus) #earliest year is 1978 (Florida)
```

```{r} 
## glaucus
gla.dates <- parse_date_time(glaucus$observed_on, "mdy") # note - the date formatting for P. glaucus was "mdy" instead of "ymd"
gla.years <- year(gla.dates)
glaucus$years <- gla.years

glaucus <- glaucus[order(glaucus$years,decreasing=T),]
glaucus

head(glaucus)
tail(glaucus) #earliest record = 1973 in TX
```

```{r} 
## diana
dia.dates <- parse_date_time(diana$observed_on, "ymd")
dia.years <- year(dia.dates)
diana$years <- dia.years

diana <- diana[order(diana$years,decreasing=T),]
diana

head(diana)
tail(diana) #earliest year is 2001 (Georgia)
```

Subsetting data, grouping by yearly increments, starting with Battus:
```{r}
battus.1970_1999 <- subset(battus, years %in% c("1970","1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980","1981", "1982", "1933", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999"), drop = FALSE)
length(battus.1970_1999$id)
## n = 10
```

Since there is so much iNat data, I am going to create histograms to group data points by year and see which years/time ranges have the most data points.
```{r}
## Battus
peaks.by.year <- aggregate(x=battus$scientific_name, by= list(battus$years), FUN=length)
peaks.by.year

years <- peaks.by.year$Group.1
length(years)
sightings <- peaks.by.year$x
length(sightings)
abundance <- data.frame(years, sightings)
abundance

b <- ggplot(abundance, aes(x=years, y=sightings)) 
b <- b + geom_bar(stat="identity", color="black",fill="grey")

b
```

```{r}
## Limenitis
peaks.by.year <- aggregate(x=limenitis$scientific_name, by= list(limenitis$years), FUN=length)
peaks.by.year

years <- peaks.by.year$Group.1
length(years)
sightings <- peaks.by.year$x
length(sightings)
abundance <- data.frame(years, sightings)
abundance

l <- ggplot(abundance, aes(x=years, y=sightings)) 
l <- l + geom_bar(stat="identity", color="black",fill="grey")

l
```
```{r}
## polyxenes
peaks.by.year <- aggregate(x=polyxenes$scientific_name, by= list(polyxenes$years), FUN=length)
peaks.by.year

years <- peaks.by.year$Group.1
length(years)
sightings <- peaks.by.year$x
length(sightings)
abundance <- data.frame(years, sightings)
abundance

p <- ggplot(abundance, aes(x=years, y=sightings)) 
p <- p + geom_bar(stat="identity", color="black",fill="grey")

p
```
```{r}
## troilus
peaks.by.year <- aggregate(x=troilus$scientific_name, by= list(troilus$years), FUN=length)
peaks.by.year

years <- peaks.by.year$Group.1
length(years)
sightings <- peaks.by.year$x
length(sightings)
abundance <- data.frame(years, sightings)
abundance

t <- ggplot(abundance, aes(x=years, y=sightings)) 
t <- t + geom_bar(stat="identity", color="black",fill="grey")

t
```
```{r}
## glaucus
peaks.by.year <- aggregate(x=glaucus$scientific_name, by= list(glaucus$years), FUN=length)
peaks.by.year

years <- peaks.by.year$Group.1
length(years)
sightings <- peaks.by.year$x
length(sightings)
abundance <- data.frame(years, sightings)
abundance

g <- ggplot(abundance, aes(x=years, y=sightings)) 
g <- g + geom_bar(stat="identity", color="black",fill="grey")

g
```
```{r}
## diana
peaks.by.year <- aggregate(x=diana$scientific_name, by= list(diana$years), FUN=length)
peaks.by.year

years <- peaks.by.year$Group.1
length(years)
sightings <- peaks.by.year$x
length(sightings)
abundance <- data.frame(years, sightings)
abundance

d <- ggplot(abundance, aes(x=years, y=sightings)) 
d <- d + geom_bar(stat="identity", color="black",fill="grey")

d
```

