---
title: "Jessica-practice-code"
author: "Jessica Herrmann"
date: '2022-07-12'
output: html_document
---

[1] Preliminary code for the Battus philenor data:
```{r}
library(curl)
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/battus_philenor.csv")
battus.data <- read.csv(b, header = TRUE, sep = ",")
head(battus.data) #for large data sets, shows the first six data points; can also use tail() to show last six data points

battus.data$Longitude #shows all data for one column
length(battus.data$Longitude) #tells you how many data points there are under Longitude column
clean.battus <- na.omit(battus.data) #deletes blank data points
length(clean.battus$Longitude) #tells you how many data points there are after deleting blanks
```

Deleting a data subset:
``` {r}

battus.data <- subset(clean.battus, Specimen.Type %in% c("Specimen", "Photograph"), drop = FALSE)
battus.data

```

Removing blank data points from "Record Number" and then removing extraneous columns, then selectively including only "Specimen" and "Photograph" under "Specimen Type" column (omitting "Sightings", which cannot be confirmed):
```{r}
length(battus$Record.Number)
clean.battus <- na.omit(battus.data)
length(clean.battus$Record.Number)

df = subset(clean.battus, select = -c(Organism.Type,Location.Notes, Observation.Notes, Updated.Date, Partner.Project, Data.Source, Submitter ) )
battus <- subset(df, Specimen.Type %in% c("Specimen", "Photograph"), drop = FALSE)
length(battus$Record.Number)

```

[2] Cleaning data for L. arthemis astyanax:
``` {r}
#Importing all L. arthemis astyanax data, then showing first six data points to verify:
library(curl)
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/limenitis_arthemis_astyanax.csv")

astyanax.data <- read.csv(b, header = TRUE, sep = ",")
head(astyanax.data)

#Delete data points with missing coordinates (either "Lat/Long" or "Longitude"). Verify changes:
astyanax.data$Longitude #shows all data for one column
length(astyanax$Longitude) #tells you how many data points there are under Longitude column
clean.astyanax <- na.omit(astyanax.data) #deletes blank data points
length(clean.astyanax$Longitude) #tells you how many data points there are after deleting blanks

length(astyanax$Record.Number)
clean.astyanax <- na.omit(astyanax.data)
length(clean.astyanax$Record.Number)

df = subset(clean.astyanax, select = -c(Organism.Type, Location.Notes, Observation.Notes, Updated.Date, Partner.Project, Data.Source, Submitter ) )
astyanax <- subset(df, Specimen.Type %in% c("Specimen", "Photograph"), drop = FALSE)
length(astyanax$Record.Number)

```
 
 
[3] Cleaning data for P. glaucus:
``` {r}
install.packages("curl")
library(curl)
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/papilio_glaucus.csv")

glaucus.data <- read.csv(b, header = TRUE, sep = ",")
head(glaucus.data)

#Deleting blanks:
glaucus$Longitude
length(glaucus$Longitude)
clean.glaucus <- na.omit(glaucus.data)
length(clean.glaucus$Longitude)

#Deleting blanks under "Record Number":
length(glaucus$Record.Number)
clean.glaucus <- na.omit(glaucus)
length(clean.glaucus$Record.Number)

#Omitting extraneous columns:
 df = subset(clean.glaucus, select = -c(Organism.Type,Location.Notes, Observation.Notes, Updated.Date, Partner.Project, Data.Source, Submitter ) )
 
#Omitting "Sightings" under "Specimen Type":
glaucus <- subset(df, Specimen.Type %in% c("Specimen", "Photograph"), drop = FALSE)
length(glaucus$Record.Number)

#Omitting all but "BF" under "Sex":
glaucus <- subset(df, Sex %in% c("BF"), drop = FALSE)
length(glaucus.data$Record.Number)

```

[4] Cleaning data for P. polyxenes:
```{r}
library(curl)
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/papilio_polyxenes.csv")

polyxenes <- read.csv(b, header = TRUE, sep = ",")
head(polyxenes)

polyxenes$Longitude
length(polyxenes$Longitude)
clean.polyxenes <- na.omit(polyxenes)
length(clean.polyxenes$Longitude)

length(polyxenes$Record.Number)
clean.polyxenes <- na.omit(polyxenes)
length(clean.polyxenes$Record.Number)

df = subset(clean.polyxenes, select = -c(Organism.Type, Location.Notes, Observation.Notes, Updated.Date, Partner.Project, Data.Source, Submitter ) )
polyxenes.data <- subset(df, Specimen.Type %in% c("Specimen", "Photograph"), drop = FALSE)
length(polyxenes.data$Record.Number)

```

[5] Cleaning data for P. troilus:
``` {r}
install.packages("curl")
library(curl)
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/5cfc0a039080ff00b279a4fc15797dadb227847d/papilio_troilus.csv")

troilus <- read.csv(b, header = TRUE, sep = ",")
tail(troilus)

troilus$Longitude
length(troilus$Longitude)
clean.troilus <- na.omit(troilus)
length(clean.troilus$Longitude)

length(troilus$Record.Number)
clean.troilus <- na.omit(troilus)
length(clean.troilus$Record.Number)

df = subset(clean.troilus, select = -c(Organism.Type, Location.Notes, Observation.Notes, Updated.Date, Partner.Project, Data.Source, Submitter ) )
troilus.data <- subset(df, Specimen.Type %in% c("Specimen", "Photograph"), drop = FALSE)
length(troilus.data$Record.Number)

```

[6] Cleaning data for S. diana:
```{r}
library(curl)
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/speyeria.diana.csv")
diana <- read.csv(b, header = TRUE, sep = ",")
head(diana)

#Deleting blanks:
diana$sex
length(diana$sex)
clean.diana <- na.omit(diana)
length(clean.diana$sex)
 
#Omitting "Sightings" under "Specimen Type":
diana.data <- subset(clean.diana, Specimen.Type %in% c("Specimen", "Photograph"), drop = FALSE)
length(diana.data$Record.Number)

#Omitting all but "F" under "Sex":
mimics <- subset(diana.data, sex == "F", drop = FALSE)
length(mimics$Record.Number)
```


Obtaining US map:

```{r}
us <- c(left = -125, bottom = 25.75, right = -67, top = 49)
us
map <- get_stamenmap(us, zoom = 5, maptype = "toner-lite") %>% ggmap() 
map
#  Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
```


[7] Practicing mapping and KDE w/ astyanax:

```{r}
# Create a coordinate column, with both your X and Y values:

b <- curl("https://raw.githubusercontent.com/butterfliesrcool/BAMONA/main/limenitis_arthemis_astyanax.csv")
astyanax <- read.csv(b, header = TRUE, sep = ",")
clean.astyanax <- na.omit(astyanax)
xy <- clean.astyanax[, c("Lat.Long", "Longitude")]

# Creating a Spatial Points dataframe:

astyanax.sp <- SpatialPointsDataFrame(coords = xy, data = clean.astyanax, proj4string = CRS("+proj=utm +zone=18 +south +datum=WGS84 +units=m +no_defs"))

# Range estimate
astyanax.mcp <- mcp(astyanax.sp, percent = 100)
astyanax.mcp

# Converting polygon into an {sf} object:
astyanax.mcp <- st_as_sf(astyanax.mcp)
```

```{r}
# Mapping the data:
astyanax.sp.sf <- st_as_sf(astyanax.sp)

q <- ggplot() + geom_sf(data = astyanax.sp.sf, color = "light pink", alpha = 0.5) + theme_bw()

#Not sure about this second map yet:
mcp1 <- q + geom_sf(data = astyanax.mcp, color = "pink", fill = "pink", alpha = 0.3)
mcp1
```

Kernel density estimate for L. arthemis astyanax:

```{r}
astyanax_k100 <- kernelUD(astyanax.sp)
image(astyanax_k100)

kern99 <- getverticeshr(astyanax_k100, percent = 99)
kern85 <- getverticeshr(astyanax_k100, percent = 85)

kern99 <- st_as_sf(kern99)
kern85 <- st_as_sf(kern85)
kern <- q + geom_sf(data = kern99, color = "pink", fill = "pink", alpha = 0.3) + 
    geom_sf(data = kern85, color = "salmon1", fill = "salmon1", alpha = 0.3)
kern
```
